version: '3.1'
services:

  api:
    build: .
    container_name: API
    ports:
      - "5029:8080"
      - "5030:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - mongo
  
  mongo:
    image: mongo:latest
    container_name: MongoDB
    ports:
      - 27017:27017
    environment: 
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: Admin@123
    volumes:
      - mongodata:/data/db

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongoadmin
      ME_CONFIG_MONGODB_ADMINPASSWORD: Admin%40123
      ME_CONFIG_MONGODB_SERVER: MongoDB
    depends_on:
      - 'mongo'

volumes:
  mongodata: 
    driver: local
